### PR TITLE
Fix WindowsPromoteStringBuffer example

### PR DESCRIPTION
**Pull request by sylveon**

### CODE REVIEW

**Comment by PRMerger5** [comment]
@sylveon : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by sylveon** [comment]
Any update on this? It hasn't progressed since February

**Comment by sylveon** [comment]
PR is now one year old without being looked at. @GrantMeStrength are you able to review this?

**Comment by GrantMeStrength** [comment]
Sorry for the delay in looking at this. Looking now.

**Comment by GrantMeStrength** [comment]
Steve - could you confirm this code sample fix? Thank you.

**Review by stevewhims — APPROVED** [review]

**Comment by stevewhims** [comment]
> Steve - could you confirm this code sample fix? Thank you.

I like it! :) It fixes a handful of issues. Approved and merged.

-Steve

**Pull request merged**
