### PR TITLE
Fix incorrect versioning in d3d12_stencil_op page

### PR DESCRIPTION
**Pull request by john-h-k**

### CODE REVIEW

**Comment by PRMerger16** [comment]
@john-h-k : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]
Thank you!

**Comment by msftgits** [comment]
[CLA assistant check](https://cla.opensource.microsoft.com/MicrosoftDocs/sdk-api?pullRequest=289) <br/>All CLA requirements met.

**Comment by stevewhims** [comment]
Hi, @john-h-k, if you could sign the CLA (see link in comment above) then I'll go ahead and merge the PR.

Thanks!
Steve

**Comment by PRMerger10** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
