### PR TITLE
Improve XAML Diagnostics docs

### PR DESCRIPTION
**Pull request by ahmed605**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@ahmed605 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@ahmed605 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@ahmed605 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger4** [comment]
@ahmed605 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger3** [comment]
@ahmed605 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by asklar — CHANGES_REQUESTED** [review]
We should make sure we are only documenting features we are planning to publicly support. Marking request changes until we have consensus internally (@GrantMeStrength fyi)

**Comment by ahmed605** [comment]
Is there any updates on this?

**Comment by ahmed605** [comment]
Hey @jwmsft, is there any updates on this? It's been over 3 months since I opened this PR

**Comment by GrantMeStrength** [comment]
Thanks for your contribution. At this time the APIs covered in this PR are not intended to be documented.
If the situation changes, we'll re-open the issue.

-John

**Comment by ahmed605** [comment]
> Thanks for your contribution. At this time the APIs covered in this PR are not intended to be documented.
> If the situation changes, we'll re-open the issue.
> 
> -John
> 

@GrantMeStrength but this PR just improves the docs for an API that is already documented, I'm not documenting any new API
Docs for this API are already available

**Comment by FireCubeStudios** [comment]
mfw the

**Comment by sylveon** [comment]
Not documenting this API is anti-competitive behavior: it prevents competing IDEs (like CLion and Rider) from implementing XAML Live VIsual Tree and XAML Hot Reload.

**Pull request closed without merging**
