### PR TITLE
WinUser.h/user32.dll: SetForegroundWindow and AllowSetForegroundWindow minor technical corrections

### PR DESCRIPTION
**Pull request by metathinker**
The SetForegroundWindow doc page remarks were not quite correct about the cases when a process can call the function to set the foreground window.

This change makes some corrections to the doc page. However, the SetForegroundWindow rules are very complex, so a full accounting of when you can set foreground would probably be too long to fit - and would encode details that might be misused to annoy the user. I thus added a generic escape clause to note that there may be additional restrictions not stated.

Pairs with https://github.com/MicrosoftDocs/win32/pull/548

### CODE REVIEW

**Comment by PRMerger9** [comment]
@metathinker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by metathinker** [comment]
Although I have reviewed the SetForegroundWindow implementation code as part of making these changes, I freely admit that I am not an expert in this area, which is very complex. Please feel free to reject this PR or refer it to reviewers who know more about user32/NTUser than me.

**Comment by PRMerger16** [comment]
@metathinker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@metathinker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@metathinker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@metathinker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@metathinker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@metathinker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by riverar** [comment]
I believe there's also missing documentation here regarding what happens when a debugger is active (e.g. Visual Studio).

**Review by jwmsft — APPROVED** [review]

**Comment by metathinker** [comment]
Man, when I wrote this PR, I was _still working for Microsoft_. Good times.

@microsoft-github-policy-service agree

**Comment by metathinker** [comment]
> I believe there's also missing documentation here regarding what happens when a debugger is active (e.g. Visual Studio).

I think a user mode debugger just running by itself won't change matters. If the debugger is debugging the old foreground process _or_ the process that calls SetForegroundWindow(), then yes, that does change things, as I wrote. But it's been 2 1/2 years since I looked at the SetForegroundWindow() source in win32k.

**Comment by jwmsft** [comment]
Sorry this PR was left sitting around for so long. And thanks for the extra info about the debugger.

**Comment by metathinker** [comment]
Life happens :)

Actually @jwmsft , it looks like your last merge commit https://github.com/MicrosoftDocs/sdk-api/pull/394/commits/b5f9f4f44d158ea4e2b3a6975fe06a3a4dd167cc accidentally erased the example code snippet on SetForegroundWindow(). Oops!

It probably disappeared because it was introduced long after this PR branch forked off the main (https://github.com/MicrosoftDocs/sdk-api/commit/dad7a561b89925bfd507d01e3be690211861fc45#diff-48cda94a27ca2d7e18faf87ebc0ae317399483537d90cce41de5b75128a7338f). We'll have to restore it - I'll leave that to you, though.

**Comment by jwmsft** [comment]
Thanks for going the extra mile and catching that. I will fix it.

**Pull request merged**
