### PR TITLE
Update nf-psapi-queryworkingsetex.md

### PR DESCRIPTION
**Pull request by zodiacon**
The process handle must have PROCESS_QUERY_INFORMATION access mask (PROCESS_VM_READ is not necessary)

### CODE REVIEW

**Comment by PRMerger14** [comment]
@zodiacon : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by PRMerger18** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Pull request merged**
