### PR TITLE
ncryptbufferdesc

### PR DESCRIPTION
**Pull request by jjhenry21**
creating file to recreate link

### CODE REVIEW

**Comment by annashott-msft** [comment]
@Karl-Bridge-Microsoft / @GrantMeStrength hoping either of you can help or point me to the proper contact in MS content.

We would like to make a new page for the NCryptBufferDesc API (part of Ncrypt) as it currently does not have a link. My team is building out an API that makes use of it and will need it documented. Please reach out to me if you need more info. Thanks!

API link broken on the CNG page, [here](https://docs.microsoft.com/en-us/windows/win32/seccng/cng-structures).

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @jjhenry21 - I can help with this. The process of creating new topics is a little more involved, esp. for Win32. I'll create a private internal branch with the new topics for you to contribute to.

**Comment by annashott-msft** [comment]
Adding @Joseph Henry (INSIGHT GLOBAL ***@***.***>

Thanks for your help! Please share the branch when it is available.

Anna

________________________________

**Comment by annashott-msft** [comment]
Hey @Karl-Bridge-Microsoft - were you able to create a private internal branch?

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @jjhenry21 - yes, I'm working on this now. It's a little more complicated as the ncrypt structs are not actual APIs, but just aliases of the BCrypt APIs. So I can't force our publishing system to publish NCrypt topics for APIs that aren't fully defined in the header. I have to figure out the best workaround with the BCrypt APIs.

**Comment by Karl-Bridge-Microsoft** [comment]
Handled privately.

**Pull request closed without merging**
