### PR TITLE
Update nf-winuser-getkeyboardtype.md

### PR DESCRIPTION
**Pull request by DJm00n**
Remove outdated  Keyboard Types and Keyboard Type->NumberOfFunction table.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by DJm00n** [comment]
Closing this. Will make a new PR

**Pull request closed without merging**
