### PR TITLE
Fixes to formatting in IOCTL documentation

### PR DESCRIPTION
**Pull request by AKhristov-SE**
I have made formatting edits, mostly changing from HTML to Markdown to make future edits easier.  Also, I fixed sample code blocks, including ones that had issues with spacing, which made the code ambiguous and confusing.

### CODE REVIEW

**Comment by AKhristov-SE** [comment]
This pull request is quickly falling behind, I'm seeing more merge conflicts I'll have to resolve. Are there any updates?

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @AKhristov-SE, thanks for the extensive work on these files. Can you resolve the merge conflicts (which might be due to a build bug fixes for the IOCTL file types) and resubmit? Thanks.

**Comment by PRMerger18** [comment]
@AKhristov-SE : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@AKhristov-SE : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Comment by AKhristov-SE** [comment]
Do not merge this just yet...

Oh, too late.

**Comment by AKhristov-SE** [comment]
Hi Karl,

Thanks for looking at this.  I will be submitting another pull request, as I was in the middle of integrating my changes when this got merged.

-Alex

**Comment by Karl-Bridge-Microsoft** [comment]
ok, i reverted that pr as soon as i saw your message

**Comment by AKhristov-SE** [comment]
Thanks. I'll have this done within the hour.

**Comment by AKhristov-SE** [comment]
Hi @Karl-Bridge-Microsoft,

I went ahead and submitted another PR, and I'll do a second one a bit later. Sorry for the confusion.  I was just worried back when I submitted this request that I'd have to redo it, and that's kind of what I ended up having to do, so it was a bit frustrating.

-Alex

**Pull request merged**
