### PR TITLE
Indicate lack of D3D12 support for non-FLIP models and add para on difference between FLIP_SEQ and FLIP_DISCARD

### PR DESCRIPTION
**Pull request by john-h-k**

### CODE REVIEW

**Comment by PRMerger16** [comment]
@john-h-k : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@john-h-k : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@john-h-k : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by stevewhims** [comment]
Don't forget the leading '/' in site-relative urls (for example, href="/windows/..." rather than href="windows/...").

Thanks!

**Pull request merged**
