### PR TITLE
Multigroup affinities - Update usermode affinity API docs

### PR DESCRIPTION
**Pull request by gipittal**

### CODE REVIEW

**Comment by PRMerger18** [comment]
@gipittal : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by GrantMeStrength** [comment]
Hi! Thanks for this PR. We're researching the changes you are making. Could I ask where you got the information you're using? Thanks!

**Comment by gipittal** [comment]
> Hi! Thanks for this PR. We're researching the changes you are making. Could I ask where you got the information you're using? Thanks!

Hello @GrantMeStrength, thanks for taking a look! I'm the dev who made these changes in the kernel.

**Comment by GrantMeStrength** [comment]
haha ok, then you probably know :-)

**Pull request merged**
