### PR TITLE
Escape backslashes

### PR DESCRIPTION
**Pull request by nxtn**

### CODE REVIEW

**Comment by PRMerger15** [comment]
@NextTurn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@NextTurn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@NextTurn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@NextTurn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@NextTurn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@NextTurn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by hkhmsft** [comment]
Thanks for your contribution, I've merged your changes and they should be live soon.

**Pull request merged**
