### PR TITLE
Update nf-winbase-openprivatenamespacea.md

### PR DESCRIPTION
**Pull request by turingcompl33t**
Fix rendering issue.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@turingcompl33t : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@lastnameholiu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@lastnameholiu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by hkhmsft** [comment]
Thanks for your contribution, I've merged your changes and they should be live soon.

**Pull request merged**
