### PR TITLE
clarify SEE_MASK_NOASYNC ShellExecuteEx flag

### PR DESCRIPTION
**Pull request by ChrisGuzak**
the system has confusing behavior, trying to clarify that with this change

### CODE REVIEW

**Comment by PRMerger3** [comment]
@ChrisGuzak : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ChrisGuzak** [comment]
@PRMerger3 can you reach out to the authors again?

**Comment by ChrisGuzak** [comment]
@jwmsft please check this.

**Review by jwmsft — APPROVED** [review]

**Comment by jwmsft** [comment]
Sorry for the delay.

**Pull request merged**
