### PR TITLE
Update drive geometry ioctl

### PR DESCRIPTION
**Pull request by hsebs**
Update IOCTL_DISK_GET_DRIVE_GEOMETRY page and IOCTL_DISK_GET_DRIVE_GEOMETRY_EX page.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@hsebs : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@hsebs : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@hsebs : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@hsebs : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]
Thanks for the thorough updates, @hsebs!

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Comment by hsebs** [comment]
@Karl-Bridge-Microsoft 
`## -parameters` doesn't work in [IOCTL pages](https://docs.microsoft.com/en-us/windows/win32/api/winioctl/ni-winioctl-ioctl_disk_get_drive_geometry).

Can I get the information about extended markdowns such as `-ioctlparamters`, `-parameters`.

**Pull request merged**
