### PR TITLE
Document REASON_CONTEXT.Reason.SimpleReasonString as const safe

### PR DESCRIPTION
**Pull request by juliekoubova**
@oldnewthing told me it was safe; everybody should know :)

### CODE REVIEW

**Comment by PRMerger18** [comment]
@juliekoubova : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by oldnewthing** [comment]
1. Should have the power management team confirm. (I was just reading source code.)
2. Same remarks apply to `ReasonStrings`. Should probably move to Remarks.
2. Wording should be less jargony.

> It is safe to pass read-only strings as the `SimpleReasonString` or `ReasonStrings` because the ` PowerCreateRequest` and `SetWaitableTimerEx` functions read from the strings and do not write to them.

**Comment by PRMerger16** [comment]
@juliekoubova : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@juliekoubova : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
