### PR TITLE
221250 - Broken link fixed

### PR DESCRIPTION
**Pull request by v-hearya**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@v-hearya : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — CHANGES_REQUESTED** [review]
The url is still a 404 for that first change. Also, rather than a naked url in the content, we could make that a markdown link, with friendly link text.

I think what I'd do is this:

`See the [Bluetooth class-of-device (CoD) codes](https://www.bluetooth.com/specifications/assigned-numbers/baseband/).`

**Review by stevewhims — CHANGES_REQUESTED** [review]
For the change in `nn-credentialprovider-icredentialprovider.md`, in general I'd say that if we can't find a document's url (and I couldn't just now trying to search for it by name on the Microsoft Download Center), then I suspect that customers won't be able to find it, either. In a case like that I'd accept that the document is lost, and I wouldn't mention it. Besides, all mentions of Windows 8 were actually meant to have been removed from the conceptual content long ago. :) Incidentally, it would be relatively rare to quote the name of a document or topic without linking to it (perhaps it's the second mention of the document's name in a paragraph, where the first mention is linked), but if one *were* to do that then I think it'd be better to format (italics, perhaps, or bold) its name, or surround it with quotes, otherwise the doc's name just disappears into the sentence, and makes it hard to read.

**Comment by PRMerger17** [comment]
@v-hearya : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by v-hearya** [comment]
Hi @stevewhims - The feedback for nn-credentialprovider-icredentialprovider.md has been implemented.

**Comment by PRMerger10** [comment]
@v-hearya : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@v-hearya : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]

**Comment by PRMerger9** [comment]
@v-hearya : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]

**Comment by PRMerger8** [comment]
@v-hearya : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]

**Pull request merged**
