### PR TITLE
Update nf-fileapi-createfilew.md

### PR DESCRIPTION
**Pull request by nxtn**
Note that "other processes" can be misleading since subsequent open operations from the same process are also denied.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@nxtn : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger4** [comment]
@mikben : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by alvinashcraft — APPROVED** [review]

**Comment by alvinashcraft** [comment]
#sign-off

**Comment by nxtn** [comment]
Note that this change is no longer intended, as the original content has been modified by #1035.

**Comment by alvinashcraft** [comment]
Thanks for the heads-up about this. This seems like it should have given a merge conflict due to the earlier change to the file. I will revert this change.

**Comment by alvinashcraft** [comment]
After the change from this PR syncs to our private repo, I'll do a PR there. Thanks again @nxtn.

**Pull request merged**
