### PR TITLE
Update ns-schannel-schannel_cred.md

### PR DESCRIPTION
**Pull request by asklar**
Add new enum values for TLS 1.3

### CODE REVIEW

**Comment by PRMerger16** [comment]
@asklar : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by asklar** [comment]
BTW @GrantMeStrength just fyi that there is a deprecation notice in the markdown towards the top, that is not rendering on the website for some reason

**Comment by asklar** [comment]
@GrantMeStrength could you take a look at this?

**Comment by GrantMeStrength** [comment]
Thanks!

**Pull request merged**
