### PR TITLE
Update CCG plugins registry key location

### PR DESCRIPTION
**Pull request by briantist**
The path to the registry key for CCG plugin COMClasses is incorrect. It should be `...\CurrentControlSet\Control\CCG\...` rather than `...CurrentControlSet\CCG\...`.

### CODE REVIEW

**Comment by PRMerger18** [comment]
@briantist : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by briantist** [comment]
@GrantMeStrength mind taking a look at this?

**Comment by briantist** [comment]
@GrantMeStrength is there anyone else who might be better positioned to review this?

**Comment by GrantMeStrength** [comment]
Thanks for the correction.

**Pull request merged**
