### PR TITLE
Fixed ambiguity of "read" vs "write".

### PR DESCRIPTION
**Pull request by paamand**

### CODE REVIEW

**Comment by GrantMeStrength** [comment]
Hey Bill, let me know if you can't OK this one.

**Comment by PRMerger12** [comment]
@paamand : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by billlattimer — APPROVED** [review]
On review with team, approving.

**Comment by billlattimer** [comment]
@GrantMeStrength approved for merge.

**Pull request merged**
