### PR TITLE
Update nf-processthreadsapi-getcurrentthreadeffectivetoken.md

### PR DESCRIPTION
**Pull request by GovM-MSFT**
Adding min supported OS as windows 8

### CODE REVIEW

**Comment by PRMerger19** [comment]
@GovM-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by GovM-MSFT** [comment]
@Karl-Bridge-Microsoft  - Thanks for the approval... but it appears I can't complete the merge, so what is the next step?

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @GovM-MSFT, I approved and then thought I should look into this further as the info should be in the topics already. Hence the delay. 

I confirmed that the info should be in the topic, but that it might've beev dropped during a docs migration a few years ago.

Only writers can finalize a PR, so I'll do that now.

**Comment by GovM-MSFT** [comment]
Oh great, thank you very much. BTW, this is the process I prefer as well. We make the suggestions, and then you guys make the final determination, by completing the PR.


Gov (Rhymes with Orange)

Work It Harder Make It Better
Do It Faster, Makes Us stronger
More Than Ever, Hour After Hour
Work Is Never Over

________________________________

**Pull request merged**
