### PR TITLE
Update ns-processthreadsapi-startupinfow.md

### PR DESCRIPTION
**Pull request by RussKie**
Remove incorrect spacing that caused the document to render incorrectly

image

### CODE REVIEW

**Comment by PRMerger9** [comment]
@RussKie : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]
Thanks @RussKie

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Pull request merged**
