### PR TITLE
Updating imfsensoractivitymonitor example code snippets with working code

### PR DESCRIPTION
**Pull request by kasumman**
* Updating imfsensoractivitymonitor example code snippets with working code
* Also updated the snippets to use c++/winrt for COM callback implementation and WIL return macros/ com ptrs etc.
* Relevant doc/sample links added.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@kasumman : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@kasumman : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@kasumman : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by drewbatgit — APPROVED** [review]

**Comment by PRMerger7** [comment]
@drewbatgit : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
