### PR TITLE
Separate WinHTTP and HTTP.SYS categories

### PR DESCRIPTION
**Pull request by Techwolfy**
The documentation for WinHTTP and HTTP.SYS is combined into a single "Windows HTTP Services (WinHTTP)" category on MSDN, which causes some confusion. This PR splits the client and server documentation into separate categories.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@Techwolfy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Techwolfy** [comment]
@stevewhims, please take a look and make sure I did this the right way; I had to create a new GUID for the new category file and I'm not sure how the content publishing system handles that.

**Comment by stevewhims** [comment]
Note that we're not using MSDN any longer (we've moved to docs.microsoft.com, or DMC for short). AFAIK, `ms.assetid:` is used only for topics *that were ever published on MSDN*. Since these new files are new for DMC, they were never published on MSDN, so I think we'll be fine. No need to remove the `ms.assetid:`; it's redundant, but it won't do any harm.

Also, just FYI, "categories" are known as "technologies". So here you've created a new technology named "winhttp". It's also worth knowing that each API reference topic contains yaml metadata indicating which "technology" that API is part of. So to indicate that a given API is part of the "winhttp" technology, we'll need to add the metadata `tech.root: winhttp` to topics for all APIs that are part of that tech.

**Review by stevewhims — APPROVED** [review]
Looks good. See my comment about moving APIs into this new technology.

**Pull request merged**
