### PR TITLE
Update nf-winnt-makelcid.md

### PR DESCRIPTION
**Pull request by DJm00n**
Add links to "Language identifier" and "Sort order identifier"

### CODE REVIEW

**Comment by PRMerger9** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@lastnameholiu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@lastnameholiu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by hkhmsft** [comment]
Thanks for the contribution. I've merged your changes and they should be live soon.

**Comment by PRMerger17** [comment]
@lastnameholiu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
