### PR TITLE
Document InternetGetCookieEx2 and InternetSetCookieEx2

### PR DESCRIPTION
**Pull request by Techwolfy**
Add documentation for the following WinINet APIs:
- Struct INTERNET_COOKIE2
- InternetFreeCookies
- InternetGetCookieEx2
- InternetSetCookieEx2

### CODE REVIEW

**Comment by PRMerger7** [comment]
@Techwolfy : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mcleanbyron** [comment]
Closing this pull request, because this will be handled via our internal repo.

**Comment by pierrecoll** [comment]
The link to INTERNET_COOKIE2 structure in InternetGetCookieEx2  is pointing to a wrong  url https://docs.microsoft.com/en-us/windows/win32/api/wininet/ns-wininet-internet-cookie2.md instead of https://docs.microsoft.com/en-us/windows/win32/api/wininet/ns-wininet-internet_cookie2

**Comment by pierrecoll** [comment]
The link is also wrong in InternetSetCookieEx2 : https://docs.microsoft.com/en-us/windows/desktop/api/wininet/ns-wininet-internet-cookie2 instead of https://docs.microsoft.com/en-us/windows/win32/api/wininet/ns-wininet-internet_cookie2

**Comment by mcleanbyron** [comment]
Thanks for pointing out these broken links! I checked in the fixes to our internal repo, and these fixes should be published to the live site in the next day or two.

**Pull request closed without merging**
