### PR TITLE
Update ns-ntddkbd-keyboard_attributes.md

### PR DESCRIPTION
**Pull request by DJm00n**
Update remarks in KEYBOARD_ATTRIBUTES structure

### CODE REVIEW

**Comment by PRMerger12** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Review by Karl-Bridge-Microsoft — CHANGES_REQUESTED** [review]
Why did you strip the links out to the .h docs and then refer readers to the docs in the SDK?

**Comment by DJm00n** [comment]
@Karl-Bridge-Microsoft Because that pages do not contain any information about “keyboard types, subtypes, scan code modes”. That info is only in comments in header files. But anyways it seems more related to older PS/2 keyboards and not very useful with modern HID keyboards. Fix me if I’m wrong.

**Comment by DJm00n** [comment]
@Karl-Bridge-Microsoft All info I have found so far is [Windows Keyboard Layouts](https://docs.microsoft.com/windows-hardware/design/whitepapers/windows-keyboard-layouts) whitepaper for OEMs, ODMs, and IHVs. It also refers [HID Review Request 42: Consumer Page Keyboard Assist Controls](https://www.usb.org/sites/default/files/hutrr42c_0.pdf).

According to these docs Windows 10 HID driver can parse *Keyboard Physical Layout* (0x2C3) usage from *Consumer Page* (0x0C) with possible values:

0. Unknown Layout 
1. 101 (e.g., US) 
2. 103 (Korea) 
3. 102 (e.g., German) 
4. 104 (e.g., ABNT Brazil) 
5. 106 (DOS/V Japan)

But **KEYBOARD\_ATTRIBUTES** in  struct only contains keyboard type and subtype.

So it seems these HID values somehow mapped to keyboard type and subtype via [HID client mapper driver for keyboards](https://docs.microsoft.com/windows-hardware/drivers/hid/keyboard-and-mouse-hid-client-drivers) (kbdhid.sys).

Could you please get a proper list of possible keyboard type/subtype in Windows 10 and how they mapped to HID usages?

Old [GetKeyboardType](https://docs.microsoft.com/windows/win32/api/winuser/nf-winuser-getkeyboardtype) WinAPI method description also contains some of possible values of keyboard types. *kbd.h* also contains a bunch of keyboard types/subtypes.

PS: Also there is *Keyboard IETF Language Tag Index* (0x2C5) usage (*Consumer Page* (0x0C)) with HID *String index* of a String Descriptor having an *IETF Language Tag* (conformant to [IETF BCP 47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt)). I have no any clue how it could be retrieved.

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @DJm00n - Thanks for the details! You have a number of different aspects logged in this PR that aren't actually valid for a PR. Requests for new/updated content need to be logged in a GitHub Issue. Unfortunately, I think the topic (https://docs.microsoft.com/en-us/windows-hardware/drivers/hid/keyboard-and-mouse-hid-client-drivers) that needs the info you're requesting doesn't support Issues. You can submit a PR against it with any updates you'd like to see and someone should be able to help you from the drivers doc team. 

I'll try to vet and process your updates for this Windows doc via this PR.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Comment by DJm00n** [comment]
@Karl-Bridge-Microsoft Looked further into SDK headers I found new undocumented (from Windows 10?) **KEYBOARD_EXTENDED_ATTRIBUTES** struct and **IOCTL_KEYBOARD_QUERY_EXTENDED_ATTRIBUTES** in `ntddkbd.h` - all that info that I said is lying in it:

```
//
// The structure used by IOCTL_KEYBOARD_QUERY_EXTENDED_ATTRIBUTES
//

#define KEYBOARD_EXTENDED_ATTRIBUTES_STRUCT_VERSION_1  (1)

typedef struct _KEYBOARD_EXTENDED_ATTRIBUTES {
    //
    // The version of this structure.
    // Only accept KEYBOARD_EXTENDED_ATTRIBUTES_STRUCT_VERSION_1 now.
    //
    UCHAR Version; 

    //
    // Keyboard Form Factor (Usage ID: 0x2C1)
    //
    UCHAR FormFactor;

    //
    // Keyboard Key Type (Usage ID: 0x2C2)
    //
    UCHAR KeyType;

    //
    // Keyboard Physical Layout (Usage ID: 0x2C3)
    //
    UCHAR PhysicalLayout;

    //
    // Vendor-Specific Keyboard Layout (Usage ID: 0x2C4)
    //
    UCHAR VendorSpecificPhysicalLayout;

    //
    // Keyboard IETF Language Tag Index (Usage ID: 0x2C5)
    //
    UCHAR IETFLanguageTagIndex;

    //
    // Implemented Keyboard Input Assist Controls (Usage ID: 0x2C6)
    //
    UCHAR ImplementedInputAssistControls;

} KEYBOARD_EXTENDED_ATTRIBUTES, *PKEYBOARD_EXTENDED_ATTRIBUTES;
```

Seems this should be documented.

**Pull request merged**
