### PR TITLE
Remove statement that SleepEx will return early

### PR DESCRIPTION
**Pull request by vtjnash**
I'm proposing deleting the following text:

> If dwMilliseconds is less than the resolution of the system clock, the thread may sleep for less than the specified length of time. If dwMilliseconds is greater than one tick but less than two, the wait can be anywhere between one and two ticks, and so on.

Since empirically when I measure the time taken by `Sleep`, this doesn't seem true, but I would like confirmation from the engineers at Microsoft.

If it's confirmed that this is not the implementation, the same correction is also needed at https://docs.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-sleep and https://docs.microsoft.com/en-us/windows/win32/sync/wait-functions#wait-functions-and-time-out-intervals

### CODE REVIEW

**Comment by PRMerger7** [comment]
@vtjnash : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by vtjnash** [comment]
Thanks for confirming!

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @vtjnash - I'm still waiting for confirmation from the dev team. I'll update the PR as soon as i get that.

**Comment by vtjnash** [comment]
bump?

**Comment by Karl-Bridge-Microsoft** [comment]
Confirmation still pending.

**Comment by vtjnash** [comment]
Bump?

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @vtjnash - A dev from the feature team replied and confirmed your findings and the revisions to the doc in your PR. Thanks for your patience!

**Comment by Karl-Bridge-Microsoft** [comment]
Would you like to update the associated docs you specify in another PR?

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Comment by vtjnash** [comment]
No thanks. Very much appreciate the confirmation though!

**Pull request merged**
