### PR TITLE
Update nf-d3d11-id3d11device-checkmultisamplequalitylevels.md

### PR DESCRIPTION
**Pull request by Const-me**
Bugfix, a critical one

### CODE REVIEW

**Comment by PRMerger10** [comment]
@Const-me : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ghost** [comment]
[CLA assistant check](https://cla.opensource.microsoft.com/MicrosoftDocs/sdk-api?pullRequest=877) <br/>All CLA requirements met.

**Comment by ghost** [comment]
[CLA assistant check](https://cla.opensource.microsoft.com/MicrosoftDocs/sdk-api?pullRequest=877) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/MicrosoftDocs/sdk-api?pullRequest=877) before we can accept your contribution.<br/><br/>:x: Const-me [sign now](https://cla.opensource.microsoft.com/MicrosoftDocs/sdk-api?pullRequest=877)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/MicrosoftDocs/sdk-api?pullRequest=877) it.</sub>

**Review by stevewhims — APPROVED** [review]

**Comment by stevewhims** [comment]
Hi, @Const-me, if you could sign the CLA (see comment in thread above) then that'll allow me to complete the PR.

Many thanks!
Steve

**Comment by PRMerger16** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by clandrew — COMMENTED** [review]
This is a really great catch! Thank you!

**Pull request merged**
