### PR TITLE
Update nf-ioapiset-getqueuedcompletionstatus.md

### PR DESCRIPTION
**Pull request by hsebs**
Add description for lpNumberOfBytesTransferred.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@hsebs : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]
thanks @hsebs!

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Pull request merged**
