### PR TITLE
Add info on Keyboard Type values from RID_DEVICE_INFO_KEYBOARD/KEYBOARD_ATTRIBUTES/GetKeyboardType()

### PR DESCRIPTION
**Pull request by DJm00n**
Added info on `dwKeyboardMode` from RID_DEVICE_INFO_KEYBOARD.
Removed outdated Keyboard Types and KeyboardType->NumberOfFunction table in GetKeyboardType() docs.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by DJm00n** [comment]
@Karl-Bridge-Microsoft any objections?

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @DJm00n - re. the keyboard type values you've added/specified... Are these just examples? Or are you stating these are the valid values?

**Comment by DJm00n** [comment]
@Karl-Bridge-Microsoft it’s possible values that windows can give. these values comes from `kbd.h` file:

```cpp
//
// Keyboard type
//
#define KEYBOARD_TYPE_GENERIC_101   (4)
//
// Keyboard Type = 7 : Japanese Keyboard
// Keyboard Type = 8 : Korean Keyboard
//
#define KEYBOARD_TYPE_JAPAN (7)
#define KEYBOARD_TYPE_KOREA (8)

// Unknown keyboard type
#define KEYBOARD_TYPE_UNKNOWN   (0x51)

....

#if (NTDDI_VERSION < NTDDI_WINXP)
//
// Keyboard Type = 7 : Japanese Keyboard
// Keyboard Type = 8 : Korean Keyboard
//
#define JAPANESE_KEYBOARD(Id)  ((Id).Type == 7)
#define KOREAN_KEYBOARD(Id)    ((Id).Type == 8)

#else

#define JAPANESE_KEYBOARD(Id)  ((Id).Type == KEYBOARD_TYPE_JAPAN)
#define KOREAN_KEYBOARD(Id)    ((Id).Type == KEYBOARD_TYPE_KOREA)

#endif
```

`ntddkbd.h` also contains macros:

```cpp
//
// ENHANCED_KEYBOARD() is TRUE if the value for keyboard type indicates an
// Enhanced (101- or 102-key) or compatible keyboard.  The result is FALSE
// if the keyboard is an old-style AT keyboard (83- or 84- or 86-key keyboard).
//
#define ENHANCED_KEYBOARD(Id) ((Id).Type == 2 || (Id).Type == 4 || FAREAST_KEYBOARD(Id))
//
// Japanese keyboard(7) and Korean keyboard(8) are also Enhanced (101-)
// or compatible keyboard.
//
#define FAREAST_KEYBOARD(Id)  ((Id).Type == 7 || (Id).Type == 8)
```

**Comment by DJm00n** [comment]
Current version of `GetKeyboardType()` docs also have these values along with ones that is not used anymore (and was removed from `kbd.h` since WinNT I guess): `IBM PC/XT or compatible (83-key) keyboard`, `Olivetti "ICO" (102-key) keyboard`, `IBM PC/AT (84-key) or similar keyboard` etc. I removed those.

**Comment by Karl-Bridge-Microsoft** [comment]
ok, confirmed. Thanks.
//
// Keyboard type
//
#define KEYBOARD_TYPE_GENERIC_101   (4)
//
// Keyboard Type = 7 : Japanese Keyboard
// Keyboard Type = 8 : Korean Keyboard
//
#define KEYBOARD_TYPE_JAPAN (7)
#define KEYBOARD_TYPE_KOREA (8)

// Unknown keyboard type
#define KEYBOARD_TYPE_UNKNOWN   (0x51)

**Comment by PRMerger10** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Pull request merged**
