### PR TITLE
[DWrite] Set the right min supported client/server

### PR DESCRIPTION
**Pull request by moi15moi**
This PR resolve the issue https://github.com/MicrosoftDocs/feedback/issues/3984

Note that there is still these interface that doesn't have any version:
- [DWRITE_CONTAINER_TYPE](https://learn.microsoft.com/en-us/windows/win32/api/dwrite_3/ne-dwrite_3-dwrite_container_type)
- [IDWriteAsyncResult](https://learn.microsoft.com/en-us/windows/win32/api/dwrite_3/nn-dwrite_3-idwriteasyncresult)
- [IDWriteColorGlyphRunEnumerator1](https://learn.microsoft.com/en-us/windows/win32/api/dwrite_3/nn-dwrite_3-idwritecolorglyphrunenumerator1)
- [IDWriteFactory4](https://learn.microsoft.com/en-us/windows/win32/api/dwrite_3/nn-dwrite_3-idwritefactory4)
- [IDWriteFactory5](https://learn.microsoft.com/en-us/windows/win32/api/dwrite_3/nn-dwrite_3-idwritefactory5)
- [IDWriteFontFace4](https://learn.microsoft.com/en-us/windows/win32/api/dwrite_3/nn-dwrite_3-idwritefontface4)
- [IDWriteFontSetBuilder1](https://learn.microsoft.com/en-us/windows/win32/api/dwrite_3/nn-dwrite_3-idwritefontsetbuilder1)
- [IDWriteInMemoryFontFileLoader](https://learn.microsoft.com/en-us/windows/win32/api/dwrite_3/nn-dwrite_3-idwriteinmemoryfontfileloader)
- [IDWriteRemoteFontFileLoader](https://learn.microsoft.com/en-us/windows/win32/api/dwrite_3/nn-dwrite_3-idwriteremotefontfileloader)
- [IDWriteRemoteFontFileStream](https://learn.microsoft.com/en-us/windows/win32/api/dwrite_3/nn-dwrite_3-idwriteremotefontfilestream)
- [IDWriteStringList](https://learn.microsoft.com/en-us/windows/win32/api/dwrite_3/nn-dwrite_3-idwritestringlist)
- [DWRITE_COLOR_GLYPH_RUN1](https://learn.microsoft.com/en-us/windows/win32/api/dwrite_3/ns-dwrite_3-dwrite_color_glyph_run1)
- [DWRITE_FILE_FRAGMENT](https://learn.microsoft.com/en-us/windows/win32/api/dwrite_3/ns-dwrite_3-dwrite_file_fragment)
- [DWRITE_FONT_PROPERTY](https://learn.microsoft.com/en-us/windows/win32/api/dwrite_3/ns-dwrite_3-dwrite_font_property)
- [DWRITE_GLYPH_IMAGE_DATA](https://learn.microsoft.com/en-us/windows/win32/api/dwrite_3/ns-dwrite_3-dwrite_glyph_image_data)

I couldn't find any documentation that could confirm in which version those where introduced.

### CODE REVIEW

**Comment by moi15moi** [comment]
@microsoft-github-policy-service agree

**Comment by moi15moi** [comment]
@Karl-Bridge-Microsoft Is there anything I can do to help you review this PR ?

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @moi15moi - thanks for the thoroughness on this! I'll check the source code for the other items in your list.

**Comment by moi15moi** [comment]
Thanks!

**Comment by moi15moi** [comment]
@Karl-Bridge-Microsoft Have you any news for the items I listed above?

**Comment by moi15moi** [comment]
@Karl-Bridge-Microsoft Have you any news for the items I listed in the first message?

**Comment by Karl-Bridge-Microsoft** [comment]
Not yet.

**Comment by moi15moi** [comment]
@Karl-Bridge-Microsoft Have you any news for the items I listed in the first message?

**Comment by moi15moi** [comment]
@Karl-Bridge-Microsoft Have you any news for the items I listed in the first message?

**Pull request merged**
