### PR TITLE
Update nf-apiquery2-isapisetimplemented.md

### PR DESCRIPTION
**Pull request by darthwing-duck**
Added the necessary lib for the API call.

### CODE REVIEW

**Comment by PRMerger14** [comment]
@juma-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by darthwing-duck** [comment]
I couldn't find the symbol without linking onecore.lib and wanted to make sure it doesn't happen to someone else.

**Comment by darthwing-duck** [comment]
onecoreuap.lib works too.

**Comment by mithrandir** [comment]
onecoreuap.lib also works? should you specify both are option?

**Pull request merged**
