### PR TITLE
Fixed PMSF_DONT_STRIP_SPACES description

### PR DESCRIPTION
**Pull request by justanotheranonymoususer**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@justanotheranonymoususer : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@justanotheranonymoususer : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@justanotheranonymoususer : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@justanotheranonymoususer : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by mcleanbyron — APPROVED** [review]

**Comment by mcleanbyron** [comment]
Thanks for catching these!

**Pull request merged**
