### PR TITLE
Fix documentation issues around Shader4ComponentMapping

### PR DESCRIPTION
**Pull request by kainino0x**

### CODE REVIEW

**Comment by kainino0x** [comment]
Working on getting approval to sign the CLA.

**Comment by stevewhims** [comment]
Thank you! Approved. I'll complete the PR when the CLA's signed.

**Review by stevewhims — APPROVED** [review]

**Review by stevewhims — APPROVED** [review]

**Comment by stevewhims** [comment]
Hi, @kainino0x, how is it going getting approval to sign the CLA? Thanks!

-Steve

**Comment by PRMerger16** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by kainino0x** [comment]
Just got approval and signed (sorry for the delay) - thanks for following up!

**Comment by PRMerger13** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
