### PR TITLE
Adding support note

### PR DESCRIPTION
**Pull request by persident**
Got this important support information form two different Senior Premier Field Engineers (Microsoft Premier Support FTEs). They got this information from the responsible product group (PG) within Microsoft.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@persident : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mcleanbyron** [comment]
Thanks for your pull request. I'm reaching out to the engineering team that owns this API to confirm the support statement in the docs for this API, and will respond as soon as I can.

**Comment by mcleanbyron** [comment]
Thank you for your contribution, and I apologize for the delay in responding. I noticed that you added this note specifically to the description for the lpComputerName parameter. Can you clarify whether this deprecation applies specifically to this optional parameter, or to the DeleteProfileW function itself?

**Comment by persident** [comment]
Thanks for your follow-up! Deprecation applies to the DeleteProfileW function, not only a parameter. Probably I have added the note to the wrong section accidentally.

**Comment by mcleanbyron** [comment]
The engineering team that owns these APIs has no record of them being deprecated. Do you still have the names of the PFE's who told you they were deprecated? If you have this information available, please reach out to me directly at mcleans-at-microsoft-dot-com. 

Based on the information I've received so far from the engineering team I'm pre-emptively closing this pull request.

**Pull request closed without merging**
