### PR TITLE
Update nf-enclaveapi-createenclave.md

### PR DESCRIPTION
**Pull request by 7eRoM**
The value of `dwSize` is NOT a multiple if page size. It only working on even amounts of MB like 2MB, 4MB, 6MB.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@7eRoM : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @7eRoM - thanks for the suggested revision. I'll try to confirm with the feature team and get specifics on the min size and why even values are required.

**Review by CodeMaxx — CHANGES_REQUESTED** [review]
Hey @7eRoM , your observation is correct. We do require the size to be a multiple of 2MB. Could you update your PR to change the wording to:

"The size must be a multiple of 2 MB."

**Comment by PRMerger19** [comment]
@7eRoM : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by 7eRoM** [comment]
Hi @CodeMaxx, it's done.

I know this request is not related to this topic but If you have access to dev-team, please review this article and ask them to fix it. I reported 5 months ago but they did not take any action!!!
https://7erom.ir/blog/windows-internals/memory-enclave-leads-to-crash/
It's related to mem-enclaves, too.

**Comment by CodeMaxx** [comment]
@7eRoM @Karl-Bridge-Microsoft I have created a new PR with some more changes here - #1258 and have included @7eRoM 's commits there.

**Comment by CodeMaxx** [comment]
@7eRoM I'll take a look at the crash you pointed here (https://7erom.ir/blog/windows-internals/memory-enclave-leads-to-crash/) to see if it still reproduces on the latest build. I am the dev owner for enclaves, but I wasn't aware of this. Thanks for pointing out!

**Comment by CodeMaxx** [comment]
@7eRoM The crash from your blog doesn't reproduce on the latest Windows 11 build, so I believe this bug was already fixed. 😊 Let me know if you face any other issues regarding enclaves.

**Comment by 7eRoM** [comment]
> @7eRoM The crash from your blog doesn't reproduce on the latest Windows 11 build, so I believe this bug was already fixed. 😊 Let me know if you face any other issues regarding enclaves.

Hey @CodeMaxx , today I tested on the latest Windows 10 x64 (Version 21H2 - Build 19044.1865) and the crash still exist.

**Comment by CodeMaxx** [comment]
@7eRoM That's right, what I meant was the bug has been fixed in the latest codebase.

**Pull request merged**
