### PR TITLE
Update nf-wuapi-iupdatedownloadcontent-get_downloadurl.md

### PR DESCRIPTION
**Pull request by sfonteneau**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@sfonteneau : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by sfonteneau** [comment]
Not Work with wsusscn2.cab (offline scan)

**Comment by mcleanbyron** [comment]
Can you please provide more context for this suggested edit? Are you saying that the IUpdateDownloadContent::get_DownloadUrl method no longer works as of Windows 10, version 2004? If so, did you determine this just from your own testing, or did someone on an engineering team at Microsoft confirm this information?

**Comment by sfonteneau** [comment]
`
Dim session : Set session = CreateObject("Microsoft.Update.Session")
Dim search  : Set search  = session.CreateUpdateSearcher()
Set UpdateServiceManager = CreateObject("Microsoft.Update.ServiceManager")
Set UpdateService = UpdateServiceManager.AddScanPackageService("Offline Sync Service", "C:\wsusscn2.cab", 1)
search.ServiceID = UpdateService.ServiceID
WScript.Echo "Searching for updates..." & vbCrLF
Set result = search.Search("Type='Software'")
WScript.Echo "Missing KBs:"
For i = 0 To result.Updates.Count -1 'last item in the collection always seems to be some kind of gibberish null.
    Set update = result.Updates.Item(i)
Next
If result.Updates.Count = 0 Then
    WScript.Echo "There are no applicable updates."
End If

Set updatesToDownload = CreateObject("Microsoft.Update.UpdateColl")
Set downloader = session.CreateUpdateDownloader() 
'For I = 0 to result.Updates.Count-1
For I = 0 to 5
    Set update = result.Updates.Item(I)
    updatesToDownload.Add(update)
Next
WScript.Echo vbCRLF & "Downloading updates..."
downloader.Updates = updatesToDownload
downloader.Download()

for i=0 to 5
  for each upd in downloader.Updates.Item(i).BundledUpdates
   for each content in upd.DownloadContents
     wscript.echo "url: " & content.DownloadURL
   next 
  next 
next 
`

I do not know if it is a bug or if it is a change of operation in the 2004 version, according to my tests this script no longer works in 2004 version but worked in all old versions since xp

So I guess it is no longer supported?
https://social.technet.microsoft.com/Forums/en-US/f01830b0-1e89-4dc7-905d-28604e952258/getdownloadurl-not-work-since-windows-10-2004?forum=deploymentlabkit

**Comment by mcleanbyron** [comment]
Can you clarify what you mean by "the script no longer works"? Are you receiving any sort of error code?

The product team that owns this API says that there have been no recent changes to the implementation of this method. If you can file feedback using Feedback Hub on your computer, that will send them logs from your computer that can help them understanding what is happening.

1.	Sign into Feedback Hub using MSA
2.	Repro issue
3.	Stop wuauserv service
4.	Submit feedback
5.	Share the aka.ms link from the feedback

The feedback hub category is “Install and Update > Downloading, installing and configuring Windows Update”. This will fetch all the relevant logs.

**Comment by sfonteneau** [comment]
I have the error: 0x8002802b when i use downloadurl
this problem had never occurred before.
I will go through Feedback Hub

the problem is simple to reproduce with the script, we immediately notice the problem.

**Comment by mcleanbyron** [comment]
Thanks for the additional info and for submitting feedback via Feedback Hub. Since there have been no changes to the implementation of this method and the product team cannot reproduce the issue you're seeing, I'm closing this pull request. 

In case it helps, you may also find these resources helpful:

- [Microsoft Q&A](https://docs.microsoft.com/answers/topics/uwp.html?sort=active&filter=all) offers relevant and timely answers to your technical problems from a community of experts and Microsoft engineers.
- For community assistance with development questions, there are our [forums](https://social.msdn.microsoft.com/Forums/newthread?category=windowsapps&forum=wpdevelop&prof=required), and [StackOverflow](https://stackoverflow.com/questions).
- The [Windows developer support](https://developer.microsoft.com/windows/support) site explains other support options.
- For developer issues, or suspected product bugs, there's [Microsoft Support](https://support.microsoft.com/contactus); a support engineer will look at the repro and see whether the issue is a Microsoft product bug, or something else. If it's a bug with a Microsoft product then the ticket will be free of charge.

**Pull request closed without merging**
