### PR TITLE
Update CIMFS documentation

### PR DESCRIPTION
**Pull request by msscotb**
Remove description of CIM_MOUNT_CHILD_ONLY flag since this behavior is not yet implemented.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@msscotb : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@msscotb : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by msscotb** [comment]
@shaheedchagani

**Comment by msscotb** [comment]
@abhijeet-gautam

**Review by QuinnRadich — APPROVED** [review]

**Comment by QuinnRadich** [comment]
#sign-off

**Pull request merged**
