### PR TITLE
Clarify destruction of SRW locks and condition variables.

### PR DESCRIPTION
**Pull request by m-ou-se**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@m-ou-se : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@m-ou-se : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Pull request merged**
