### PR TITLE
Correct link to Resource Types page in EnumResourceNamesA.

### PR DESCRIPTION
**Pull request by Warpten**
The documentation for `EnumResourceNamesA` links to the DirectX 10 resource types. Unless I'm misunderstanding the API, this is just not correct. Linked to the proper (?) page instead.

Remark: Not sure what's about that ^M being removed on commit. Is it a special control character for documentation or a typo?

### CODE REVIEW

**Comment by PRMerger6** [comment]
@Warpten : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Warpten** [comment]
I have no idea why github thinks there's a conflict?

**Comment by PRMerger9** [comment]
@lastnameholiu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by hkhmsft** [comment]
Thanks for your contribution, I've merged your changes and they should be live soon.

**Pull request merged**
