### PR TITLE
Use sane arg names for TimerProc

### PR DESCRIPTION
**Pull request by justanotheranonymoususer**

### CODE REVIEW

**Comment by PRMerger20** [comment]
@justanotheranonymoususer : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @justanotheranonymoususer - thanks for the feedback. This issue was fixed through a global patch on our doc processing. Closing this issue as fixed.

**Comment by justanotheranonymoususer** [comment]
@Karl-Bridge-Microsoft was it committed? Now it says `unnamedParam1` to `unnamedParam4`.

**Comment by Karl-Bridge-Microsoft** [comment]
These params are not explicitly named in the header. This new auto-naming convention was adopted to convey that more clearly. Please see similar callback functions with the same defs: https://docs.microsoft.com/en-us/windows/win32/api/winuser/nc-winuser-sendasyncproc, https://docs.microsoft.com/en-us/windows/win32/api/winuser/nc-winuser-propenumprocexw, etc.

**Comment by justanotheranonymoususer** [comment]
So why not name them wherever needed?
For example, here there are variable names:
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nc-winuser-hookproc

**Comment by Karl-Bridge-Microsoft** [comment]
They are defined in the source code: typedef LRESULT (CALLBACK* HOOKPROC)(int code, WPARAM wParam, LPARAM lParam);

The callback you're suggesting we create param names does not: typedef VOID (CALLBACK* TIMERPROC)(HWND, UINT, UINT_PTR, DWORD);

This is an automated feature of our publishing pipeline to ensure the docs reflect the source as much as possible.

**Comment by justanotheranonymoususer** [comment]
OK. Perhaps it's worth suggesting to whoever maintains the source code to add param names for documentation.

**Pull request closed without merging**
