### PR TITLE
Update ns-winuser-rid_device_info_keyboard.md

### PR DESCRIPTION
**Pull request by DJm00n**
Add some possible valued for keyboard `dwType` that are still in use in Windows. Added info on `dwKeyboardMode`.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger8** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by DJm00n** [comment]
Closing this. Will make a new PR

**Pull request closed without merging**
