### PR TITLE
Clarify, improve style and grammar.

### PR DESCRIPTION
**Pull request by glenn-slayden**

### CODE REVIEW

**Comment by PRMerger14** [comment]
@glenn-slayden : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@glenn-slayden : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Review by glenn-slayden — COMMENTED** [review]
Thanks.

**Pull request merged**
