### PR TITLE
Remove `ID2D1DrawTransform` from the remarks

### PR DESCRIPTION
**Pull request by rickbrew**
`ID2D1AnalysisTransform` cannot be implemented by an `ID2D1DrawTransform` (pixel shader). I've tried it and it 100% does not work, this seems to be an error in the documentation.

### CODE REVIEW

**Comment by stevewhims** [comment]
Thanks, Rick, I'm investigating.

**Comment by rickbrew** [comment]
Thanks @stevewhims . 

@Sergio0694 (MSFT) may be able to help, he has some interactions with the Direct2D team.

I'm not 100.000% sure that `ID2D1DrawContext` cannot implement `ID2D1AnalysisTransform` -- but, it didn't work for me, and there are no example/samples that show how to do it. I didn't see any `QueryInterface` calls asking my `ID2D1DrawTransform` for an `ID2D1AnalysisTransform`. Either this documentation is wrong, or it's incomplete.

**Comment by stevewhims** [comment]
Apologies, still making enquires. :)

**Comment by rickbrew** [comment]
No worries, I'm in no rush

**Review by stevewhims — APPROVED** [review]

**Pull request merged**
