### PR TITLE
Update nf-wincrypt-certopenserverocspresponse.md

### PR DESCRIPTION
**Pull request by amelonpie**
Add more details on the synchronous behavior and the description for the already supported asynchronous behavior.

### CODE REVIEW

**Comment by amelonpie** [comment]
@microsoft-github-policy-service agree [company="{Philips}"]

**Comment by amelonpie** [comment]
@microsoft-github-policy-service agree company="Philips"

**Comment by amelonpie** [comment]
@microsoft-github-policy-service agree

**Review by alvinashcraft — APPROVED** [review]
Thank you for adding the sync/async clarification to this doc. Looks good!

**Pull request merged**
