### PR TITLE
Escape backslashes in multiple docs

### LINKED ISSUE #877: Missing a backslash in pipe name
**Link to article:**
https://docs.microsoft.com/en-us/windows/desktop/api/winbase/nf-winbase-createnamedpipea
https://docs.microsoft.com/en-us/windows/desktop/api/Winbase/nf-winbase-createmailslota

**Problem:**
The article says the pipe name must have the form `\.\pipe<i>pipename`. It should be `\\.\pipe\pipename`. Similar for CreateMailslotA.

### PR DESCRIPTION
**Pull request by xiaoyinl**
Since backslashes should be escaped in markdown, double backslashes in code are rendered as a single backslash, which is confusing for users. This PR fixes this issue in CreateMailslotW, CreateMailslotA, CreateNamedPipeA, WaitNamedPipeA pages.

Fixes MicrosoftDocs/feedback#877

### CODE REVIEW

**Comment by PRMerger9** [comment]
@xiaoyinl : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@xiaoyinl : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by xiaoyinl** [comment]
@lastnameholiu I have resolved the conflict, could you please review? Thank you!

**Comment by hkhmsft** [comment]
Thanks for your contribution, I've merged your changes and they should be live soon.

**Pull request merged**
