### PR TITLE
Update ResourceMinLODClamp field description in all SRV helped structs

### PR DESCRIPTION
**Pull request by navkagleb**
Updated `ResourceMinLODClamp` field description in all SRV helper structs. Also added remark related to usage `MipLevels` field with  `MostDetailedMip` and `ResourceMinLODClamp`.

### CODE REVIEW

**Comment by navkagleb** [comment]
@microsoft-github-policy-service agree [company="navkagleb"]

**Comment by navkagleb** [comment]
@microsoft-github-policy-service agree

**Comment by stevewhims** [comment]
Hi, @navkagleb, and thanks for this PR.

To make it easier for me to make the same edits to seven copies of the same content, I've just transferred these changes to my own PR. It's in a private repo, so you might not be able to access it: https://cpubwin.visualstudio.com/win32/_git/sdk-api/pullrequest/20138. My changes will be live probably within an hour.

Thanks again!
-Steve

**Comment by navkagleb** [comment]
nice. thanks)

**Pull request closed without merging**
