### PR TITLE
dwFlags can be zero

### PR DESCRIPTION
**Pull request by AlexGuteniev**

### CODE REVIEW

**Comment by PRMerger9** [comment]
@AlexGuteniev : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]
Thanks @AlexGuteniev.

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Pull request merged**
