### PR TITLE
Update various WASAPI reference docs to refer to "process loopback mode", added in Win10 20348

### PR DESCRIPTION
**Pull request by zhuman**
This updates the main places people look at for initializing an IAudioClient: IMMDevice::Activate and the IAudioClient interface page itself. This also fixes a broken link in the AUDIOCLIENT_ACTIVATION_PARAMS page.

### CODE REVIEW

**Comment by zhuman** [comment]
I've just learned that IMMDevice::Activate actually doesn't support this parameter(this is something we should document though), it's intended only for the "UWP-branded" factory variant that takes a device interface ID string (which needs to have a magic string passed). I will update the branch shortly with the findings.

**Comment by drewbatgit** [comment]
@zhuman Just acknowledging this PR. It sounds like I'm waiting for you to finalize your updates. Please @ me when you're ready for me to review and complete the PR.

**Comment by drewbatgit** [comment]
@zhuman Just checking on the status of this PR. Is this something you are still investigating?

**Comment by zhuman** [comment]
Yes it's still on my backlog :-P

**Review by drewbatgit — APPROVED** [review]

**Comment by drewbatgit** [comment]
@zhuman - Sorry, I forgot to check the existing comments and went ahead approved this. Do you need me to back these changes out?

**Pull request merged**
