### PR TITLE
Update ns-winuser-rawmouse.md

### PR DESCRIPTION
**Pull request by DJm00n**
Fix `usButtonFlags` and `usButtonData` not rendered after #743.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by DJm00n** [comment]
@jwmsft any updates?

**Comment by DJm00n** [comment]
@jwmsft ping

**Review by jwmsft — APPROVED** [review]

**Comment by jwmsft** [comment]
@DJm00n, thank you. Sorry for the delay.

**Pull request merged**
