### PR TITLE
More details on proper (S/G)etThreadDescription dynamic linking on 2016/1607

### PR DESCRIPTION
**Pull request by tringi**

### CODE REVIEW

**Comment by PRMerger13** [comment]
@tringi : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by tringi** [comment]
Note:  I have no idea why the editor diffed the `## -see-also` lines. They are identical.

**Comment by PRMerger12** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Pull request merged**
