### PR TITLE
Update nf-fwpmu-fwpmengineopen0.md

### PR DESCRIPTION
**Pull request by NetMage**
Fix incorrect link from SEC_WINNT_AUTH_IDENTITY_W to SEC_WINNT_AUTH_IDENTITY_A

### CODE REVIEW

**Comment by PRMerger13** [comment]
@NetMage : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]

**Comment by stevewhims** [comment]
Hi, it looks like the CLA hasn't been signed yet (please see comment in the thread above). If you could sign that, then the button will appear on this end for me to complete the PR. Thanks! :)

**Comment by PRMerger5** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by NetMage** [comment]
Done!

**Pull request merged**
