### PR TITLE
Add info on IOCTL_KEYBOARD_QUERY_EXTENDED_ATTRIBUTES and KEYBOARD_EXTENDED_ATTRIBUTES struct

### PR DESCRIPTION
**Pull request by DJm00n**
Information gained from ntddkbd.h and [HID Usage Table Review Request 42: Consumer Page Keyboard Assist Controls](https://www.usb.org/sites/default/files/hutrr42c_0.pdf)

### CODE REVIEW

**Comment by PRMerger15** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by DJm00n** [comment]
See my comments in #351

**Comment by DJm00n** [comment]
Summon @Karl-Bridge-Microsoft :)

**Comment by DJm00n** [comment]
@Karl-Bridge-Microsoft  @GrantMeStrength any comments?

**Comment by DJm00n** [comment]
@Karl-Bridge-Microsoft any news on this?

**Comment by Karl-Bridge-Microsoft** [comment]
Hi @DJm00n - I have to do some due diligence on this, esp. as there are new topics being added. 

My review.
Vetting by feature team.
TOC changes required. 

A number of moving parts, so please be patient and I'll get to this asap. Note, I might have to close this PR without merging and make the updates on a private, internal branch.

Thanks.

**Comment by DJm00n** [comment]
@Karl-Bridge-Microsoft Thank you for follow up.

**Comment by Karl-Bridge-Microsoft** [comment]
@DJm00n - files have been updated in an internal PR. If any concerns, please open a new issue/pr on those updated topics. Thanks.

**Pull request closed without merging**
