### PR TITLE
Update nf-winsock2-wsapoll.md

### PR DESCRIPTION
**Pull request by compnerd**
- Fix the list element tags for elements of UDP notes.
- Fix the URL links.
- Remove some extraneous spaces.

### CODE REVIEW

**Comment by PRMerger9** [comment]
@compnerd : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]
I'll approve this in the interest of expediency. We do have many cases such as this, where HTML and markdown are mixed together, and often not co-existing well. However, ideally we'd be moving further toward universal use of markdown, rather than further away from it.

**Comment by compnerd** [comment]
@stevewhims - ah, okay, thats good to know, I'll keep that in mind for future edits.  I tend to run into issues like this often and tend to just put up PRs to at least fix the rendering - it makes reading the docs easier.

**Comment by stevewhims** [comment]
Thanks, @compnerd! Thank you: you definitely fixed the rendering nicely, which is the main priority! If you do change HTML to markdown, ever, the only gotcha really is in Win32 enumeration topics (due to a, hopefully temporary, situation with our content build system), where it's not possible to use markdown within the description of each of the enumerated constants. In that case, we need to stick with HTML in there. Also, if you want to author an emdash in any topic, I use `&mdash;`, which is of course an HTML entity. Apart from that, markdown should work ok everywhere else. :)

Thanks again!
Steve

**Pull request merged**
