### PR TITLE
Update nc-winsvc-lpservice_main_functiona.md

### PR DESCRIPTION
**Pull request by xiaoyinl**
Fix missing Parameters descriptions. The parameter names must match the ones in the header file.

### CODE REVIEW

**Comment by PRMerger20** [comment]
@xiaoyinl : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@xiaoyinl : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@xiaoyinl : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@lastnameholiu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@lastnameholiu : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
