### PR TITLE
Can you confirm that this commit works?

### PR DESCRIPTION
**Pull request by hsebs**
I changed formatting from ioctl to function in #136.

But new formatting doesn't work in [IOCTL_DISK_GET_DRIVE_GEOMETRY](https://docs.microsoft.com/en-us/windows/win32/api/winioctl/ni-winioctl-ioctl_disk_get_drive_geometry) page.

### CODE REVIEW

**Comment by PRMerger6** [comment]
@hsebs : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Karl-Bridge-Microsoft** [comment]
@hsebs - thanks for all the work you're doing in these docs. Unfortunately, the issue your experiencing is caused by a docs engineering issue. A bug is logged against the team and a fix is on the way (no ETA). Please re-activate this PR if the issue is still present in a month or two. Thanks.

**Comment by Karl-Bridge-Microsoft** [comment]
@hsebs - please clarify.

**Comment by hsebs** [comment]
@Karl-Bridge-Microsoft 
Thank you for the reply.

Before closing the issue left before this commit, I made that reference to indicate the reason.

Sorry for this making you uncomfortable.

Can I continue working the old way like #136 ?

**Pull request closed without merging**
