### PR TITLE
Replace â€” by hyphens

### PR DESCRIPTION
**Pull request by bdbai**

### CODE REVIEW

**Comment by ghost** [comment]
[CLA assistant check](https://cla.opensource.microsoft.com/MicrosoftDocs/sdk-api?pullRequest=306) <br/>All CLA requirements met.

**Comment by PRMerger8** [comment]
@bdbai : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by drewbatgit — APPROVED** [review]

**Comment by PRMerger13** [comment]
@mcleanbyron : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@mcleanbyron : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@mcleanbyron : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@mcleanbyron : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by mcleanbyron — APPROVED** [review]

**Pull request merged**
