### PR TITLE
Update nf-cfgmgr32-cm_register_notification.md

### PR DESCRIPTION
**Pull request by DJm00n**
Update `CM_Register_Notification` description.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by DJm00n** [comment]
@GrantMeStrength any updates?

**Comment by DJm00n** [comment]
@GrantMeStrength any updates?

**Comment by DJm00n** [comment]
@GrantMeStrength any updates? :)

**Comment by DJm00n** [comment]
@GrantMeStrength any updates?

**Comment by DJm00n** [comment]
@GrantMeStrength ping ))

**Comment by GrantMeStrength** [comment]
Confirming..

**Comment by DJm00n** [comment]
@GrantMeStrength anything I can do to get this merged?

**Comment by DJm00n** [comment]
@stevewhims can you please take a look?

**Review by stevewhims — APPROVED** [review]

**Comment by stevewhims** [comment]
> @stevewhims can you please take a look?

Yes, thanks for these changes! Sorry about the delay!

-Steve

**Pull request merged**
