### PR TITLE
Update library name to Windowscodecs.lib

### PR DESCRIPTION
**Pull request by Gr8Escape**
Ran into an issue after adding WIC code to my project. Turns out the libname is incorrect

### CODE REVIEW

**Comment by PRMerger10** [comment]
@Gr8Escape : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — APPROVED** [review]
Thank you! Note that the lib goes next to its own field.

**Comment by stevewhims** [comment]
Hi, @Gr8Escape, I'm unable to merge this pull request at the moment. Do you mind looking for the comment above asking about signing the Contributor License Agreement? Once that's done I'll go ahead and merge this.

Thanks!
Steve

**Comment by PRMerger18** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
