### PR TITLE
Update nf-d3d10shader-id3d10shaderreflectiontype-getmembertypename.md

### PR DESCRIPTION
**Pull request by RogerDX9**
Fixed document descritption and return value

### CODE REVIEW

**Comment by PRMerger16** [comment]
@spoiltos : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by stevewhims — COMMENTED** [review]
I have a mail out to the feature team to double-check that the descriptions here are accurate, so please stand by. The "(function name contains a typo, should be GetMemberName)" part looks like product feedback, so we can't merge that into the content. Once I have all the info, I'll make a new commit to this PR and then approve and merge it. Thanks!

**Review by stevewhims — APPROVED** [review]
With input from the feature team, I did an edit pass on the PR.

**Comment by stevewhims** [comment]
Hi, @spoiltos, I'm ready to merge and complete this PR, it's just currently blocked on your signing the license/cla. Please see the check item in the UI below. Thanks!

**Comment by PRMerger9** [comment]
@stevewhims : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by RogerDX9** [comment]
Hi @stevewhims, I've signed the license/cla. Also I like your new changes, thanks a lot!

**Comment by stevewhims** [comment]
Thank you, @spoiltos! :)

**Pull request merged**
