### PR TITLE
QoS API Updates and Timer Resolution changes

### PR DESCRIPTION
**Pull request by mabellon-msft**
Updates wording to reflect QoS naming and links to forthcoming QoS docs (separate PR).

Documents new timer resolution behavior for Windows 11 and related API changes to control this behavior.

### CODE REVIEW

**Comment by PRMerger8** [comment]
@mabellon-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by PRMerger7** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Pull request merged**
