### PR TITLE
Update nf-uiautomationcoreapi-uiaraisenotificationevent.md

### PR DESCRIPTION
**Pull request by douggeoffray**

### CODE REVIEW

**Comment by PRMerger9** [comment]
@douggeoffray : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — COMMENTED** [review]
Hi @douggeoffray, your update is HTML, not standard markdown.

**Comment by PRMerger18** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Pull request merged**
