### PR TITLE
Fix formatting and incredibly misleading link

### PR DESCRIPTION
**Pull request by ratijas**
The topic in question obviously has nothing to do with hardware device drivers.

### CODE REVIEW

**Comment by PRMerger17** [comment]
@ratijas : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Comment by ratijas** [comment]
@Karl-Bridge-Microsoft I thought there's a [huge refactoring](https://github.com/MicrosoftDocs/sdk-api/commit/0797841e74f7d55cba99a08948b601604799ef07) in process, which is why I intentionally omitted fixing other links. Looks like there's still tons of them broken at the moment. Is it worth fixing manually?

**Comment by Karl-Bridge-Microsoft** [comment]
I believe the refactoring you're referring to is absolute to relative links. The links I updated were to non-existent msdn topics (with no redirects). I'm sure there are many of these. I just did an ad-hoc update as I was reviewing your PR anyway. Thanks for checking! You're welcome to fix any broken links you find! :-)

**Comment by ratijas** [comment]
OK, thanks for the info.

**Comment by ratijas** [comment]
Oh wait, what is going on here? There are two different pages with the same name. Which one should be linked, e.g. at the bottom of [this page](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-enumresourcenamesa)?

- https://docs.microsoft.com/en-us/windows/win32/menurc/resources
- https://docs.microsoft.com/en-us/windows/win32/api/_menurc/

**Comment by Karl-Bridge-Microsoft** [comment]
One includes the conceptual content while the other is just the API ref. It's a symptom of how the old win32 docs are structured.

**Pull request merged**
