### PR TITLE
Update MEM_EXTENDED_PARAMETER documentation

### PR DESCRIPTION
**Pull request by mspll**
- Add extended attribute flag descriptions
- Fix MEM_ADDRESS_REQUIREMENTS links
- Reflect the fact that MemExtendedParameterNumaNode is a 64-bit parameter

### CODE REVIEW

**Comment by PRMerger4** [comment]
@mspll : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger5** [comment]
@mspll : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by mspll** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by GrantMeStrength** [comment]
Thank you for the updates! Confirmed by PL and CM.
-John

**Pull request merged**
