### PR TITLE
Update nf-cfgmgr32-cm_get_devnode_status.md

### PR DESCRIPTION
**Pull request by DJm00n**
In addition to #1113

### CODE REVIEW

**Comment by PRMerger16** [comment]
@DJm00n : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by DJm00n** [comment]
@GrantMeStrength any updates on this?

**Comment by DJm00n** [comment]
@GrantMeStrength any updates?

**Comment by DJm00n** [comment]
@GrantMeStrength just a follow up :)

**Comment by DJm00n** [comment]
@GrantMeStrength PING ))

**Comment by DJm00n** [comment]
@GrantMeStrength anything I can do to get this merged?

**Comment by DJm00n** [comment]
@stevewhims can you please take a look?

**Review by stevewhims — APPROVED** [review]

**Comment by stevewhims** [comment]
> @stevewhims can you please take a look?

Yes, thank you! :) Sorry for the delay!

-Steve

**Pull request merged**
