### PR TITLE
Update ni-winioctl-ioctl_disk_get_drive_geometry.md

### PR DESCRIPTION
**Pull request by hsebs**
Update parameters section

### CODE REVIEW

**Comment by PRMerger14** [comment]
@hsebs : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@hsebs : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by hsebs** [comment]
I think it would be better to use parameters of DeviceIoControl than ioctl parameters.

What do you think about this?

**Comment by PRMerger7** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by PRMerger8** [comment]
@Karl-Bridge-Microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by Karl-Bridge-Microsoft** [comment]
#sign-off

**Pull request merged**
