### PR TITLE
Document MiniDumpWithAvxXStateContext, MiniDumpWithIptTrace, and MiniDumpScanInaccessiblePartialPages.

### PR DESCRIPTION
**Pull request by AraHaan**
For some reasons documentations was not provided to these.

I did my best guess as to what these are for by googling what all I did not know (like the AvxXStateContext part of the flag to try to figure out what type of data it includes).

### CODE REVIEW

**Comment by PRMerger14** [comment]
@AraHaan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@AraHaan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by AraHaan** [comment]
I think I finally found out what the IPT Trace flag does, it adds the processor trace I think as well.

according to what I found about IPT traces so far from [here](https://github.com/intel/libipt).

**Comment by PRMerger6** [comment]
@AraHaan : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by AraHaan** [comment]
I think the documentations should be good now (if I am correct on the MiniDumpWithAvxXStateContext flag at the moment). I think I now understand what the last flag does and made some changes after opening the pr.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Pull request merged**
